### ISSUE TITLE
Could this still work if Ollama serve is running on another machine?

### ISSUE THREAD

**Issue by TijuanaKez** [0ssamaak0/SiriLLama#3]
I prefere to have frontend stuff on my Macs, but Ollama running on a linux box with a 3090.
Works great for OpenWebUI etc.

**Comment by 0ssamaak0** [comment]
Ofc yes. But you have to expose the local host to be a public link. I often use some cloud service to test larger LLMs.

[check this](https://medium.com/@PubNub/what-is-ngrok-9f35088c6dcf)

If everything on the same Wifi. You don't even have to tunnel. Just access through your private IP.
