### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by sogergely** [0ssamaak0/SiriLLama#7]
First of all your work is amazing! Thank you for sharing this project with us :+1: 
Could you please provide me some information about how to use Ngrok with your project?

Ngrok wont let me expose my localhost without a port, but the shortcut requires one.

**Comment by sogergely** [comment]
And if its possible could you tell me how to use this with ngrok? Do i have to tunnel localhost without port or with port? Ngrok only allowing me to expose localhost with ports specified.

**Comment by 0ssamaak0** [comment]
Hi, did you found out a way to do this?
+ Can you give me a context why are you using Ngrok? Are you using it from a device outside your network?

**Comment by sogergely** [comment]
Yes, im willing to use it from a device outside my network.

**Comment by 0ssamaak0** [comment]
[This version should work](https://www.icloud.com/shortcuts/f9439a8c91994bb0980b8fb4e394487a)

I made it in a hurry please verify it works, but I just removed the port from the link so you send directly to ngrok URL. When you setup it will ask you for ngrok url instead

<img width="1054" alt="Screenshot 2024-09-28 at 9 55 24 AM" src="https://github.com/user-attachments/assets/08aa392a-8273-49c7-9843-0fa7454b136b">

**Comment by sogergely** [comment]
It was working with the original shortcut, you should leave the port empty and i provided my link with http instead of https. Its working perfectly, thank you for the quick response!

A small notice when you are using multimodal:
If you choose to take photos in HEIF format (you change your this under format in the camera app settings) it wont recognise the photo at all. If you choose the most compatible format, it will work perfectly.

**Comment by 0ssamaak0** [comment]
Very good! Can you submit a PR to add this to the README? Add it as point 6 [here](https://github.com/0ssamaak0/SiriLLama?tab=readme-ov-file#running-sirillama-) before **Good Bye (point 6 now)**

**Comment by sogergely** [comment]
I believe this should takes place in the config section or you should create an extra good to know section with this multimodal and ngrok informations

**Comment by 0ssamaak0** [comment]
> I believe this should takes place in the config section or you should create an extra good to know section with this multimodal and ngrok informations

The second idea is good, I think you can add it after **Other LLM Providers**

**Comment by sogergely** [comment]
I believe i made the changes but you have to accept it
